// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUhQUD667TCUbR-gLCYDsj3-pqYTjdLXo',
    appId: '1:17201573206:web:05a900c5d218b01d0c3af7',
    messagingSenderId: '17201573206',
    projectId: 'flutter-firebase-chat-ap-c7ef2',
    authDomain: 'flutter-firebase-chat-ap-c7ef2.firebaseapp.com',
    storageBucket: 'flutter-firebase-chat-ap-c7ef2.firebasestorage.app',
    measurementId: 'G-B66CRFFLHT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAo7WAIMkRUE36FD6aB9G5Rx9XLjlakM44',
    appId: '1:17201573206:android:d0e221ea04a41e2e0c3af7',
    messagingSenderId: '17201573206',
    projectId: 'flutter-firebase-chat-ap-c7ef2',
    storageBucket: 'flutter-firebase-chat-ap-c7ef2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4e2K3DjAD7xmqzjWG4_EHiH1UqMZBDmU',
    appId: '1:17201573206:ios:7d15065f3617ae460c3af7',
    messagingSenderId: '17201573206',
    projectId: 'flutter-firebase-chat-ap-c7ef2',
    storageBucket: 'flutter-firebase-chat-ap-c7ef2.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4e2K3DjAD7xmqzjWG4_EHiH1UqMZBDmU',
    appId: '1:17201573206:ios:7d15065f3617ae460c3af7',
    messagingSenderId: '17201573206',
    projectId: 'flutter-firebase-chat-ap-c7ef2',
    storageBucket: 'flutter-firebase-chat-ap-c7ef2.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUhQUD667TCUbR-gLCYDsj3-pqYTjdLXo',
    appId: '1:17201573206:web:565d3fd9b31f0fe70c3af7',
    messagingSenderId: '17201573206',
    projectId: 'flutter-firebase-chat-ap-c7ef2',
    authDomain: 'flutter-firebase-chat-ap-c7ef2.firebaseapp.com',
    storageBucket: 'flutter-firebase-chat-ap-c7ef2.firebasestorage.app',
    measurementId: 'G-ZCRKKEQ0KH',
  );
}
